# Site settings
title: Concepts, Architecture, and Algorithms
email: iamwil@gmail.com
description: "We believe that engineers like working in an environment where we're continually learning. To work with excellent peers is a perk in itself, and we would like to continually get better as programmers. The focus is to learn ideas we can carry with us, rather than things that can easily be made obsolete."
baseurl: "/caa"
url: ""
twitter_username: jekyllrb
github_username:  jekyll
safe: true
lsi: false

# Build settings
markdown: kramdown
permalink: pretty
